import type { AgentType } from '@/types/agents'

export interface AgentProfile {
  id: AgentType
  name: string
  emoji: string
  role: string
  bio: string
  personality: string[]
  specialties: string[]
  skills: string[]
  whenToUse: string[]
  squad: SquadId
}

export type SquadId = 'estrategia' | 'producao' | 'inteligencia' | 'operacoes' | 'performance'

export interface Squad {
  id: SquadId
  name: string
  tagline: string
  color: string
  colorBg: string
  colorBorder: string
  colorText: string
  agents: AgentProfile[]
}

export const SQUADS: Squad[] = [
  {
    id: 'estrategia',
    name: 'Squad Estratégia',
    tagline: 'O Cérebro — planejamento, orquestração e memória institucional.',
    color: 'amber',
    colorBg: 'bg-amber-500/10',
    colorBorder: 'border-amber-500/30',
    colorText: 'text-amber-400',
    agents: [
      {
        id: 'oracle',
        name: 'ORACLE',
        emoji: '🧠',
        role: 'Diretor de Marketing IA',
        bio: 'O ORACLE é o agente maestro da Agency OS. Ele pensa como um CMO com 15 anos de mercado digital: analisa o cenário completo do cliente, monta estratégias de campanha do zero e direciona cada tarefa para o agente certo. É quem transforma caos em plano de ação.',
        personality: ['Estratégico', 'Direto', 'Analítico', 'Orientado a resultados'],
        specialties: ['Orquestração de agentes', 'Planejamento estratégico', 'Diagnóstico de marca', 'Briefing de campanha'],
        skills: ['Análise de contexto', 'Plano de ação', 'Delegação inteligente', 'Diagnóstico de mercado', 'ROI strategy'],
        whenToUse: ['Quando precisar de um plano completo do zero', 'Para diagnósticos iniciais de cliente', 'Ao montar uma campanha de lançamento', 'Para orquestrar múltiplos agentes em paralelo'],
        squad: 'estrategia',
      },
      {
        id: 'nexus',
        name: 'NEXUS',
        emoji: '🤝',
        role: 'Gerente de Relacionamento com Clientes',
        bio: 'O NEXUS é o elo entre a agência e o cliente. Mestre em comunicação estratégica, ele transforma reuniões em resumos executivos, garante follow-ups no tempo certo e mantém o cliente sempre informado sem sobrecarregar a equipe.',
        personality: ['Empático', 'Profissional', 'Organizado', 'Comunicativo'],
        specialties: ['Resumos de reunião', 'Follow-up estratégico', 'Apresentações para cliente', 'Alinhamento de expectativas'],
        skills: ['Redação executiva', 'Gestão de expectativas', 'Status de projeto', 'Comunicação de resultados'],
        whenToUse: ['Após reuniões com clientes', 'Para preparar apresentações de resultado', 'Quando precisar de um follow-up profissional', 'Para alinhar escopo e expectativas'],
        squad: 'estrategia',
      },
      {
        id: 'genesis',
        name: 'GENESIS',
        emoji: '⚙️',
        role: 'Criador e Arquiteto de Agentes',
        bio: 'O GENESIS é o engenheiro que constrói a inteligência por trás dos bastidores. Ele projeta novos agentes do zero: escreve system prompts, define personas, mapeia capacidades e testa comportamentos. É o arquiteto do time.',
        personality: ['Técnico', 'Criativo', 'Metódico', 'Inovador'],
        specialties: ['Criação de system prompts', 'Design de personas IA', 'Arquitetura de agentes', 'Teste de comportamentos'],
        skills: ['Prompt engineering', 'Design de fluxo', 'Criação de personas', 'Documentação técnica'],
        whenToUse: ['Para criar um agente customizado para um nicho', 'Quando quiser expandir o time com novas especialidades', 'Para testar diferentes abordagens de IA'],
        squad: 'estrategia',
      },
      {
        id: 'lore',
        name: 'LORE',
        emoji: '📚',
        role: 'Guardião da Memória Institucional',
        bio: 'O LORE é a memória viva da agência. Ele guarda decisões passadas, processos validados, metodologias criadas, cases de sucesso e aprendizados acumulados. Consulte o LORE antes de reinventar a roda.',
        personality: ['Preciso', 'Referenciado', 'Conservador', 'Confiável'],
        specialties: ['Memória histórica', 'Documentação de processos', 'Cases de sucesso', 'Metodologias internas'],
        skills: ['Recuperação de contexto', 'Documentação', 'Análise histórica', 'Gestão do conhecimento'],
        whenToUse: ['Para consultar decisões e processos passados', 'Ao onboarding de um novo colaborador', 'Para entender como a agência trabalha', 'Quando quiser basear uma decisão em histórico real'],
        squad: 'estrategia',
      },
    ],
  },
  {
    id: 'producao',
    name: 'Squad Produção',
    tagline: 'A Fábrica — conteúdo, criativos, vídeo e distribuição em escala.',
    color: 'violet',
    colorBg: 'bg-violet-500/10',
    colorBorder: 'border-violet-500/30',
    colorText: 'text-violet-400',
    agents: [
      {
        id: 'vera',
        name: 'VERA',
        emoji: '✍️',
        role: 'Copywriter de Alta Conversão',
        bio: 'A VERA escreve como quem conhece a dor do cliente de cor. Especialista em copy High-Ticket, ela cria textos que vendem pelo emocional e convertem pelo racional. De legenda de Instagram a funil de lançamento, cada palavra tem um propósito.',
        personality: ['Persuasiva', 'Empática', 'Direta', 'Criativa'],
        specialties: ['Copy High-Ticket', 'Funis de vendas', 'Anúncios de performance', 'Storytelling de marca'],
        skills: ['Headlines', 'CTAs', 'Email marketing', 'Landing pages', 'Roteiro de VSL', 'Legendas Instagram'],
        whenToUse: ['Para criar copy de anúncios e landing pages', 'Funil de lançamento de produto', 'Emails de nutrição e vendas', 'Legendas e scripts para redes sociais'],
        squad: 'producao',
      },
      {
        id: 'marco',
        name: 'MARCO',
        emoji: '🎬',
        role: 'Roteirista e Diretor de Conteúdo',
        bio: 'O MARCO pensa em cenas, cortes e ganchos. Roteirista especializado em vídeo curto e longo, ele sabe que os primeiros 3 segundos decidem tudo. Do Reels de 15s ao podcast de 1h, o MARCO entrega o script pronto para gravar.',
        personality: ['Criativo', 'Visual', 'Dinâmico', 'Storyteller'],
        specialties: ['Roteiros de Reels e TikTok', 'Scripts de podcast', 'Vídeos institucionais', 'YouTube Shorts'],
        skills: ['Gancho (0-3s)', 'Estrutura narrativa', 'Direção de cenas', 'CTA de vídeo', 'Linguagem falada'],
        whenToUse: ['Ao produzir conteúdo em vídeo para o cliente', 'Para criar uma série de Reels ou TikToks', 'Roteiro para YouTube ou podcast', 'Vídeo de vendas (VSL)'],
        squad: 'producao',
      },
      {
        id: 'atlas',
        name: 'ATLAS',
        emoji: '🎨',
        role: 'Diretor de Arte e Criativos',
        bio: 'O ATLAS transforma briefings em linguagem visual. Ele cria prompts de alto nível para ferramentas de IA generativa e entrega diretrizes de arte completas: estilo, paleta, composição e mood. Seu output é referência para qualquer designer.',
        personality: ['Visual', 'Criativo', 'Detalhista', 'Estético'],
        specialties: ['Prompts para Midjourney/DALL-E', 'Briefing de design', 'Brand identity visual', 'Direção de arte'],
        skills: ['Composição visual', 'Paleta de cores', 'Tipografia', 'Mood boards', 'Estilo fotográfico'],
        whenToUse: ['Para criar criativos de anúncio', 'Desenvolvimento de identidade visual', 'Direção de fotografia de produto', 'Briefing para designer ou ferramenta de IA'],
        squad: 'producao',
      },
      {
        id: 'vox',
        name: 'VOX',
        emoji: '🎙️',
        role: 'Produtor de Conteúdo de Áudio',
        bio: 'O VOX dá voz à estratégia. Ele escreve scripts otimizados para narração, com ritmo, pausas e ênfases que tornam cada narração natural e envolvente. Integrado com ElevenLabs, o VOX é o motor por trás do clone de voz da Agency OS.',
        personality: ['Rítmico', 'Expressivo', 'Técnico', 'Detalhista'],
        specialties: ['Scripts para narração', 'Clonagem de voz', 'Podcasts', 'Locuções institucionais'],
        skills: ['Redação para áudio', 'Indicação de pausas', 'Entonação', 'Ritmo de fala', 'Formato para ElevenLabs'],
        whenToUse: ['Para produzir narrações com a voz clonada do cliente', 'Scripts de podcast ou audioblog', 'Locução para vídeos e institucionais', 'Conteúdo de áudio em escala'],
        squad: 'producao',
      },
      {
        id: 'pulse',
        name: 'PULSE',
        emoji: '📱',
        role: 'Especialista em Social Media e Engajamento',
        bio: 'O PULSE vive nas redes sociais. Ele gerencia a presença digital com estratégias de engajamento que transformam seguidores em comunidade. Cria DM scripts, responde comentários no tom da marca e mantém o algoritmo feliz.',
        personality: ['Engajador', 'Atual', 'Empático', 'Estratégico'],
        specialties: ['Comunidade digital', 'DM scripts', 'Stories e Reels', 'Calendário editorial'],
        skills: ['Engajamento orgânico', 'Gestão de comentários', 'Estratégia de stories', 'Community management'],
        whenToUse: ['Para criar estratégias de engajamento', 'DM scripts de prospecção', 'Gestão da comunidade do cliente', 'Calendário de conteúdo semanal'],
        squad: 'producao',
      },
      {
        id: 'cipher',
        name: 'CIPHER',
        emoji: '🔐',
        role: 'Especialista em Distribuição de Conteúdo',
        bio: 'O CIPHER conhece os algoritmos de cada plataforma como a palma da mão. Ele otimiza posts para maximizar alcance, define os melhores horários de publicação, gera hashtags estratégicas e adapta o mesmo conteúdo para múltiplos canais.',
        personality: ['Analítico', 'Técnico', 'Orientado a dados', 'Metódico'],
        specialties: ['SEO de conteúdo', 'Hashtags estratégicas', 'Timing de publicação', 'Adaptação multiplataforma'],
        skills: ['Algoritmos Instagram/LinkedIn/TikTok', 'Otimização de alcance', 'Metadados de post', 'Scheduling estratégico'],
        whenToUse: ['Para otimizar posts antes de publicar', 'Criar listas de hashtags por nicho', 'Adaptar conteúdo para diferentes plataformas', 'Maximizar alcance orgânico'],
        squad: 'producao',
      },
      {
        id: 'flux',
        name: 'FLUX',
        emoji: '⚡',
        role: 'Especialista em Automação e Integrações',
        bio: 'O FLUX elimina trabalho manual. Ele mapeia processos, identifica gargalos e constrói fluxos de automação no n8n, Make e Zapier. Cada workflow que o FLUX cria libera horas do time para o que realmente importa.',
        personality: ['Sistemático', 'Técnico', 'Eficiente', 'Inovador'],
        specialties: ['n8n e Make (Integromat)', 'Zapier', 'Webhooks e APIs', 'Blueprints de automação'],
        skills: ['Mapeamento de processo', 'Lógica condicional', 'Integrações REST', 'Gestão de erros', 'Triggers e ações'],
        whenToUse: ['Para automatizar relatórios e entregas', 'Integrar ferramentas do cliente', 'Criar notificações automáticas', 'Eliminar tarefas manuais repetitivas'],
        squad: 'producao',
      },
    ],
  },
  {
    id: 'inteligencia',
    name: 'Squad Inteligência',
    tagline: 'Os Analistas — pesquisa, dados e entendimento profundo do mercado.',
    color: 'cyan',
    colorBg: 'bg-cyan-500/10',
    colorBorder: 'border-cyan-500/30',
    colorText: 'text-cyan-400',
    agents: [
      {
        id: 'vance',
        name: 'VANCE',
        emoji: '🎯',
        role: 'Estrategista de Marca e Marketing',
        bio: 'O VANCE pensa grande. Especialista em posicionamento de marca, ele analisa concorrência, desenvolve arquitetura de mensagem e cria calendários editoriais que sustentam um posicionamento de autoridade a longo prazo.',
        personality: ['Estratégico', 'Analítico', 'Visionário', 'Estruturado'],
        specialties: ['Posicionamento de marca', 'Análise de concorrência', 'Calendário editorial', 'Arquitetura de mensagem'],
        skills: ['Brand strategy', 'Análise de mercado', 'Diferenciação', 'Mensagem central', 'Proposta de valor'],
        whenToUse: ['Para definir ou reposicionar uma marca', 'Análise competitiva detalhada', 'Criar a estratégia editorial de um cliente', 'Desenvolvimento de proposta de valor'],
        squad: 'inteligencia',
      },
      {
        id: 'iris',
        name: 'IRIS',
        emoji: '🔎',
        role: 'Pesquisadora e Analista de Mercado',
        bio: 'A IRIS é a detetive do time. Ela mergulha fundo em mercados, comportamentos e tendências para entregar análises que ninguém mais tem. Cada pesquisa da IRIS vem com dados, fontes e insights acionáveis.',
        personality: ['Curiosa', 'Precisa', 'Analítica', 'Confiável'],
        specialties: ['Pesquisa de mercado', 'Análise de tendências', 'Mapeamento de concorrentes', 'Comportamento do consumidor'],
        skills: ['Desk research', 'Análise de tendências', 'Relatórios estruturados', 'Síntese de dados', 'Benchmarking'],
        whenToUse: ['Antes de lançar um produto ou campanha', 'Para entender o mercado de um novo cliente', 'Análise competitiva aprofundada', 'Identificar oportunidades e ameaças'],
        squad: 'inteligencia',
      },
      {
        id: 'vector',
        name: 'VECTOR',
        emoji: '📊',
        role: 'Especialista em Analytics e Dados',
        bio: 'O VECTOR transforma números em decisões. Ele analisa métricas de todas as plataformas digitais, identifica padrões invisíveis e gera relatórios que mostram exatamente o que está funcionando e o que precisa mudar.',
        personality: ['Analítico', 'Preciso', 'Visual', 'Orientado a dados'],
        specialties: ['Meta Ads analytics', 'Google Analytics', 'Instagram insights', 'Relatórios de performance'],
        skills: ['Análise de CTR/CPC/ROAS', 'Funis de conversão', 'Dashboards', 'A/B test analysis', 'Forecasting'],
        whenToUse: ['Para análise mensal de resultados', 'Quando uma campanha não está performando', 'Relatórios de performance para o cliente', 'Identificar campanhas com melhor ROI'],
        squad: 'inteligencia',
      },
      {
        id: 'prism',
        name: 'PRISM',
        emoji: '🌈',
        role: 'Especialista em Cultura Digital e Audiências',
        bio: 'O PRISM entende gente. Ele mapeia personas com profundidade cirúrgica, identifica tendências culturais antes de viralizar e conecta comportamentos de audiência ao posicionamento da marca de forma que ressoa de verdade.',
        personality: ['Empático', 'Cultural', 'Criativo', 'Perceptivo'],
        specialties: ['Mapeamento de personas', 'Cultura digital', 'Gen Z e Millennials', 'Comportamento de consumo'],
        skills: ['Criação de ICP', 'Análise cultural', 'Tendências de plataforma', 'Insight de audiência', 'Segmentação psicográfica'],
        whenToUse: ['Para criar o ICP detalhado de um cliente', 'Entender comportamentos de um nicho', 'Conectar a marca a movimentos culturais', 'Segmentar audiências para campanhas'],
        squad: 'inteligencia',
      },
    ],
  },
  {
    id: 'operacoes',
    name: 'Squad Operações',
    tagline: 'A Gestão — onboarding, qualidade, CRM e saúde financeira.',
    color: 'emerald',
    colorBg: 'bg-emerald-500/10',
    colorBorder: 'border-emerald-500/30',
    colorText: 'text-emerald-400',
    agents: [
      {
        id: 'bridge',
        name: 'BRIDGE',
        emoji: '🚪',
        role: 'Especialista em Onboarding de Clientes',
        bio: 'O BRIDGE garante que todo cliente novo entre pela porta certa. Ele conduz o processo de onboarding com precisão: coleta as informações certas, alinha expectativas desde o início e prepara o briefing inicial que alimenta todos os outros agentes.',
        personality: ['Acolhedor', 'Organizado', 'Detalhista', 'Empático'],
        specialties: ['Onboarding estruturado', 'Coleta de briefing', 'Alinhamento de expectativas', 'Setup inicial de cliente'],
        skills: ['Checklist de entrada', 'Briefing inicial', 'Apresentação do processo', 'Documentação de cliente'],
        whenToUse: ['Na entrada de um cliente novo', 'Para padronizar o processo de onboarding', 'Criação do briefing base do cliente', 'Alinhamento de escopo e entregáveis'],
        squad: 'operacoes',
      },
      {
        id: 'aegis',
        name: 'AEGIS',
        emoji: '🛡️',
        role: 'Gestor de Qualidade e Aprovação',
        bio: 'O AEGIS é o guardião do padrão. Antes de qualquer entrega chegar ao cliente, passa pelo AEGIS — ele revisa alinhamento com briefing, identifica inconsistências e garante que só o melhor sai da agência.',
        personality: ['Criterioso', 'Construtivo', 'Detalhista', 'Rigoroso'],
        specialties: ['Revisão de entregas', 'Alinhamento com briefing', 'Fluxo de aprovação', 'Controle de qualidade'],
        skills: ['QA de conteúdo', 'Checklist de qualidade', 'Feedback construtivo', 'Gestão de revisões', 'Aprovação interna'],
        whenToUse: ['Antes de enviar qualquer entrega ao cliente', 'Para revisar campanhas completas', 'Gestão do fluxo de aprovação interno', 'Garantir consistência com o DNA da marca'],
        squad: 'operacoes',
      },
      {
        id: 'harbor',
        name: 'HARBOR',
        emoji: '💼',
        role: 'Especialista em CRM e Relacionamento Comercial',
        bio: 'O HARBOR gerencia o pipeline de negócios com visão estratégica. Ele qualifica leads, prepara propostas comerciais, acompanha negociações abertas e identifica oportunidades de expansão com clientes ativos.',
        personality: ['Estratégico', 'Persuasivo', 'Organizado', 'Orientado a fechamento'],
        specialties: ['Pipeline de vendas', 'Propostas comerciais', 'Qualificação de leads', 'Upsell e cross-sell'],
        skills: ['CRM management', 'Proposta executiva', 'Negociação', 'Follow-up comercial', 'Identificação de oportunidades'],
        whenToUse: ['Para preparar uma proposta comercial', 'Organizar e qualificar o pipeline', 'Follow-up com leads em negociação', 'Identificar oportunidades de upsell'],
        squad: 'operacoes',
      },
      {
        id: 'ledger',
        name: 'LEDGER',
        emoji: '📋',
        role: 'Especialista Financeiro da Agência',
        bio: 'O LEDGER cuida dos números. Ele analisa a rentabilidade de cada conta, prepara relatórios financeiros precisos, calcula o ROI das campanhas e ajuda a precificar serviços com margem saudável.',
        personality: ['Preciso', 'Analítico', 'Estratégico', 'Confiável'],
        specialties: ['Análise de rentabilidade', 'ROI de campanhas', 'Precificação de serviços', 'Relatórios financeiros'],
        skills: ['MRR e LTV', 'CAC', 'Margem de contribuição', 'Fluxo de caixa', 'Relatórios executivos'],
        whenToUse: ['Para calcular o ROI de uma campanha', 'Definir pricing de um novo serviço', 'Relatório financeiro mensal', 'Análise de rentabilidade por cliente'],
        squad: 'operacoes',
      },
    ],
  },
  {
    id: 'performance',
    name: 'Squad Performance',
    tagline: 'Os Closers — tráfego pago, crescimento e retenção de clientes.',
    color: 'rose',
    colorBg: 'bg-rose-500/10',
    colorBorder: 'border-rose-500/30',
    colorText: 'text-rose-400',
    agents: [
      {
        id: 'volt',
        name: 'VOLT',
        emoji: '⚡',
        role: 'Especialista em Tráfego Pago e Performance',
        bio: 'O VOLT faz dinheiro rodar. Especialista em Meta Ads, Google Ads e TikTok Ads, ele cria estruturas de campanha que maximizam ROAS e minimizam CAC. Cada real investido em tráfego com o VOLT tem um destino calculado.',
        personality: ['Analítico', 'Orientado a ROI', 'Direto', 'Data-driven'],
        specialties: ['Meta Ads', 'Google Ads', 'TikTok Ads', 'Estratégia de performance'],
        skills: ['Estrutura de campanha', 'Segmentação avançada', 'Análise de ROAS/CTR/CPC', 'Copies de anúncio', 'Estratégia de lances'],
        whenToUse: ['Para criar ou otimizar campanhas de tráfego', 'Quando o ROAS está abaixo do esperado', 'Estruturação de uma conta de anúncios do zero', 'Análise mensal de performance de mídia paga'],
        squad: 'performance',
      },
      {
        id: 'surge',
        name: 'SURGE',
        emoji: '🚀',
        role: 'Growth Hacker da Agência',
        bio: 'O SURGE pensa em escala. Ele encontra as alavancas de crescimento que ninguém mais enxerga, propõe experimentos ousados e otimiza funis de conversão com velocidade e precisão. Crescimento não é sorte — é método.',
        personality: ['Disruptivo', 'Analítico', 'Ágil', 'Orientado a experimentos'],
        specialties: ['Growth experiments', 'Otimização de funil', 'Aquisição e retenção', 'A/B testing'],
        skills: ['Mapeamento de funil', 'Hipóteses testáveis', 'Plano de experimento', 'CRO', 'Estratégias de aquisição'],
        whenToUse: ['Para encontrar gargalos no funil de vendas', 'Quando o crescimento estagnado', 'Planejar experimentos de crescimento', 'Otimizar taxa de conversão de landing pages'],
        squad: 'performance',
      },
      {
        id: 'anchor',
        name: 'ANCHOR',
        emoji: '⚓',
        role: 'Especialista em Customer Success',
        bio: 'O ANCHOR mantém clientes felizes e pagando. Ele monitora a saúde de cada conta, conduz QBRs estratégicos, detecta sinais de churn antes que aconteçam e cria planos de expansão que aumentam o LTV.',
        personality: ['Proativo', 'Empático', 'Estratégico', 'Orientado a valor'],
        specialties: ['NPS e health score', 'QBR executivo', 'Retenção de clientes', 'Planos de expansão'],
        skills: ['Análise de satisfação', 'Prevenção de churn', 'Upsell estratégico', 'Relatório de valor entregue', 'Plano de sucesso do cliente'],
        whenToUse: ['Para revisar a saúde de uma carteira de clientes', 'Preparar QBR ou reunião de resultado', 'Quando um cliente mostra sinal de churn', 'Criar plano de expansão de contrato'],
        squad: 'performance',
      },
    ],
  },
]
